version: '3'
services:
    mongodb:
        image: mongo:6.0.2
        container_name: mongodb
        env_file:
        - mongo.env
        volumes:
        - mongodbdata:/data/db
        networks:
            - db
        ports:
         - "27017"
    flask:
        build:  app
        image: imageflask
        container_name: flask
        env_file:
        - mongo.env
        depends_on:
        - mongodb
        networks:
            frontend:
            db:
        ports:
            - "5000"
        
    nginx:
        build: nginx
        container_name: nginx
        ports:
            - "80:80"
        volumes: 
        - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
        - ./app/server/:/usr/share/nginx/html/static
        networks:
            frontend:
        depends_on:
            - flask
networks:
    frontend:
    db:
volumes:
    mongodbdata:
    
